CREATE DATABASE Pilares;
USE Pilares;
CREATE TABLE Profesor(
idProf INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(20),
Area VARCHAR(20)
);
CREATE TABLE Alumno(
idAlumn INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(20),
FechaNac DATE
);
CREATE TABLE Taller(
idTaller INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR (20),Area VARCHAR(20),
Capacidad INT, idProf INT UNSIGNED,
FOREIGN KEY (idProf) REFERENCES Profesor (idProf)
);